repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0
    hooks:
      - id: golangci-lint
      - id: golangci-lint-config-verify
  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        args:
          - --config=./.checkmake.ini
  - repo: https://github.com/zrootorg/kubeconform-precommit-hook.git
    rev: v0.0.1
    hooks:
      - id: kubeconform
        args:
          - -p./kubernetes
