apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: apiserver
images:
  - name: apiserver
    newName: ghcr.io/tcuthbert/apiserver
    newTag: 0.2.0
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
